### ISSUE TITLE
The example setup is invalid

### ISSUE THREAD

**Issue by pranaygp** [langri-sha/screeps-webpack-plugin#25]
2 things wrong with the example code on your README:

1. You a have a typo
2. It was a pain to figure out how to get this to work (when it commits to screeps, nothing happens since screeps expects a `module.exports` but instead, webpack builds to a `var` target by default. This is easily fixed by passing in the right [output.libraryTarget](https://webpack.js.org/configuration/output/#output-librarytarget) to  the webpack config (the exported file should export as a commonjs module, not a variable)

This should significantly help anyone else planning to use the repo 👍 

I've made a PR for these issues

**Comment by langri-sha** [comment]
Thanks for the help @pranaygp
